add_newline = false
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$ruby\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "yellow"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'

[ruby]
symbol = " "
format = '[$symbol($version )]($style)'
